/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/concept/{node_slug}/ripples": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Concept Ripples */
    get: operations["concept_ripples_concept__node_slug__ripples_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/edge/{edge_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Edge */
    get: operations["edge_edge__edge_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/feed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Feed */
    get: operations["feed_feed_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/story/{story_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Story */
    get: operations["story_story__story_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/story/{story_id}/ripples": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Story Ripples */
    get: operations["story_ripples_story__story_id__ripples_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Certainty
     * @enum {string}
     */
    Certainty: "established" | "emerging" | "speculative";
    /**
     * ClaimState
     * @enum {string}
     */
    ClaimState:
      | "observed_effect"
      | "established_mechanism"
      | "emerging_signal"
      | "conditional_pathway"
      | "not_shown";
    /** ConceptRippleEdgeResponse */
    ConceptRippleEdgeResponse: {
      certainty: components["schemas"]["Certainty"];
      /** Contested */
      contested: boolean;
      /** Direction */
      direction: string;
      /** Edge Id */
      edge_id: string;
      /** Evidence */
      evidence: components["schemas"]["EvidenceResponse"][];
      /** From Node */
      from_node: string;
      /** High Impact */
      high_impact: boolean;
      /** Hop */
      hop: number;
      /** Lag */
      lag: string;
      /** Mechanism */
      mechanism: string;
      provenance: components["schemas"]["Provenance"];
      /** Required Condition */
      required_condition: string;
      /** Strength */
      strength: string;
      /** To Node */
      to_node: string;
    };
    /** ConceptRippleResponse */
    ConceptRippleResponse: {
      /**
       * Cached
       * @default false
       */
      cached: boolean;
      /** Concept Slug */
      concept_slug: string;
      /** Edges */
      edges: components["schemas"]["ConceptRippleEdgeResponse"][];
      /** Max Depth */
      max_depth: number;
      /** Nodes */
      nodes: components["schemas"]["RippleNodeResponse"][];
    };
    /** EdgeDetailResponse */
    EdgeDetailResponse: {
      certainty: components["schemas"]["Certainty"];
      /** Contested */
      contested: boolean;
      /** Contested Views */
      contested_views: {
        [key: string]: unknown;
      }[];
      /** Direction */
      direction: string;
      /** Edge Id */
      edge_id: string;
      /** Evidence */
      evidence: components["schemas"]["EvidenceResponse"][];
      from_node: components["schemas"]["RippleNodeResponse"];
      /** High Impact */
      high_impact: boolean;
      /** Lag */
      lag: string;
      /** Mechanism */
      mechanism: string;
      provenance: components["schemas"]["Provenance"];
      /** Required Condition */
      required_condition: string;
      /** Strength */
      strength: string;
      to_node: components["schemas"]["RippleNodeResponse"];
    };
    /** ErrorResponse */
    ErrorResponse: {
      /** Detail */
      detail: string;
    };
    /** EvidenceResponse */
    EvidenceResponse: {
      /** Directness */
      directness: string;
      /** Evidence Id */
      evidence_id: string;
      /** Publisher */
      publisher: string;
      /** Source Type */
      source_type: string;
      /** Supports */
      supports: boolean;
      /** Title */
      title: string;
      /**
       * Url
       * Format: uri
       */
      url: string;
    };
    /** FeedItemResponse */
    FeedItemResponse: {
      /** Domain */
      domain: string;
      /** Fixture */
      fixture: boolean;
      /** Headline */
      headline: string;
      /** Origin Location */
      origin_location: string;
      /** Prominence Reasons */
      prominence_reasons: string[];
      /**
       * Published At
       * Format: date-time
       */
      published_at: string;
      /** Sources */
      sources: components["schemas"]["StorySourceResponse"][];
      /** Story Id */
      story_id: string;
    };
    /** FeedResponse */
    FeedResponse: {
      /** Items */
      items: components["schemas"]["FeedItemResponse"][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Database */
      database: string;
      /** Status */
      status: string;
    };
    /**
     * Provenance
     * @enum {string}
     */
    Provenance: "curated" | "ai_suggested";
    /** RippleNodeResponse */
    RippleNodeResponse: {
      /** Label */
      label: string;
      /** Node Id */
      node_id: string;
      /** Node Type */
      node_type: string;
    };
    /** StoryDetailResponse */
    StoryDetailResponse: {
      /** Domain */
      domain: string;
      /** Entities */
      entities: string[];
      /** Event Status */
      event_status: string;
      /** Fixture */
      fixture: boolean;
      /** Headline */
      headline: string;
      /** Mapped Nodes */
      mapped_nodes: string[];
      /** Origin Location */
      origin_location: string;
      /** Prominence Reasons */
      prominence_reasons: string[];
      /**
       * Published At
       * Format: date-time
       */
      published_at: string;
      /** Sources */
      sources: components["schemas"]["StorySourceResponse"][];
      /** Story Id */
      story_id: string;
      /** Themes */
      themes: string[];
    };
    /** StoryRippleEdgeResponse */
    StoryRippleEdgeResponse: {
      certainty: components["schemas"]["Certainty"];
      /** Certainty Reasons */
      certainty_reasons: string[];
      claim_state: components["schemas"]["ClaimState"];
      /** Condition Met */
      condition_met: boolean;
      /** Contested */
      contested: boolean;
      /** Direction */
      direction: string;
      /** Edge Id */
      edge_id: string;
      /** Event Status */
      event_status: string;
      /** Evidence */
      evidence: components["schemas"]["EvidenceResponse"][];
      /** From Node */
      from_node: string;
      /** High Impact */
      high_impact: boolean;
      /** Hop */
      hop: number;
      /** Lag */
      lag: string;
      /** Mechanism */
      mechanism: string;
      provenance: components["schemas"]["Provenance"];
      /** Publish */
      publish: boolean;
      /** Required Condition */
      required_condition: string;
      /** Story Id */
      story_id: string;
      /** Strength */
      strength: string;
      /** To Node */
      to_node: string;
    };
    /** StoryRippleResponse */
    StoryRippleResponse: {
      /** Branches */
      branches: string[][];
      /**
       * Cached
       * @default false
       */
      cached: boolean;
      /** Edges */
      edges: components["schemas"]["StoryRippleEdgeResponse"][];
      /** Fixture */
      fixture: boolean;
      /** Main Path */
      main_path: string[];
      /** Max Depth */
      max_depth: number;
      /** Nodes */
      nodes: components["schemas"]["RippleNodeResponse"][];
      /** Story Id */
      story_id: string;
    };
    /** StorySourceResponse */
    StorySourceResponse: {
      /** Excerpt */
      excerpt: string;
      /** Outlet */
      outlet: string;
      /** Paywalled */
      paywalled: boolean;
      /**
       * Url
       * Format: uri
       */
      url: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  concept_ripples_concept__node_slug__ripples_get: {
    parameters: {
      query?: {
        depth?: number;
      };
      header?: never;
      path: {
        node_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConceptRippleResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edge_edge__edge_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        edge_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EdgeDetailResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  feed_feed_get: {
    parameters: {
      query?: {
        domain?: string;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeedResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  story_story__story_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        story_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StoryDetailResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  story_ripples_story__story_id__ripples_get: {
    parameters: {
      query?: {
        depth?: number;
      };
      header?: never;
      path: {
        story_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StoryRippleResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
